'use strict';
const $=s=>document.querySelector(s),enc=new TextEncoder(),decode=b=>Uint8Array.from(atob(b),c=>c.charCodeAt(0));
let sessionKey=null,manifest=null,config=null,worker=null,saving=false;
const cacheName='nmp-encrypted-v2',shell=['./','index.html','gate.js','sw.js','vault.json','manifest.webmanifest','icon.svg','icon-192.png','icon-512.png'];
async function cachedFetch(p){try{const r=await fetch(p,{cache:'no-store'});if(r.ok)return r;}catch{}const c=await caches.open(cacheName),hit=await c.match(new URL(p,location.href));if(hit)return hit;throw Error('Connect to download the presentation first.');}
async function rpc(type,extra={}){const target=navigator.serviceWorker.controller||worker;if(!target)throw Error('Refresh the page to enable secure viewing.');return new Promise((resolve,reject)=>{const ch=new MessageChannel(),t=setTimeout(()=>reject(Error('Secure viewer did not respond. Refresh and try again.')),15000);ch.port1.onmessage=e=>{clearTimeout(t);e.data.error?reject(Error(e.data.error)):resolve(e.data);};target.postMessage({type,...extra},[ch.port2]);});}
navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='NEED_SESSION'&&e.ports[0])e.ports[0].postMessage(sessionKey?{key:sessionKey,manifest}:{});});
const ready=(async()=>{if(!crypto.subtle||!('serviceWorker'in navigator))throw Error('Open this page in Safari over HTTPS.');const r=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await navigator.serviceWorker.ready;worker=r.active;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));})();
$('#unlock').onsubmit=async e=>{e.preventDefault();$('#submit').disabled=true;$('#status').textContent='Unlocking…';try{await ready;config=await(await cachedFetch('vault.json')).json();const base=await crypto.subtle.importKey('raw',enc.encode($('#password').value),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:decode(config.salt),iterations:config.iterations,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt']);const data=await(await cachedFetch(config.manifest.url)).arrayBuffer();let parsed;try{parsed=JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(config.manifest.iv),additionalData:enc.encode('manifest')},key,data)));}catch{throw Error('Incorrect password, or the saved presentation needs updating.');}sessionKey=key;manifest=parsed;await rpc('UNLOCK',{key,manifest});$('#password').value='';$('#gate').hidden=true;$('#presentation').hidden=false;$('#presentation').src='./content/index.html'+location.hash;}catch(err){$('#status').textContent=err.message;}finally{$('#submit').disabled=false;}};
async function saveOffline(onProgress=()=>{}){if(saving)return;saving=true;try{if(!manifest)throw Error('Unlock first.');const paths=[...shell,config.manifest.url,...new Set(Object.values(manifest.files).flatMap(f=>f.chunks.map(c=>c.url)))],cache=await caches.open(cacheName);let n=0;for(const p of paths){const u=new URL(p,location.href);if(shell.includes(p)||!await cache.match(u)){const r=await cachedFetch(u.href);if(!r.ok)throw Error('Download interrupted; tap Save offline to resume.');await cache.put(u,r);}onProgress(++n/paths.length);}await navigator.storage?.persist?.();return true;}finally{saving=false;}}
async function isOfflineReady(){if(!manifest)return false;const cache=await caches.open(cacheName);for(const p of [...shell,config.manifest.url,...Object.values(manifest.files).flatMap(f=>f.chunks.map(c=>c.url))])if(!await cache.match(new URL(p,location.href)))return false;return true;}
async function lock(){sessionKey=null;manifest=null;$('#presentation').src='about:blank';$('#presentation').hidden=true;await rpc('LOCK');$('#gate').hidden=false;$('#status').textContent='Locked.';$('#password').focus();}
window.NMPVault=Object.freeze({saveOffline,isOfflineReady,lock});
ready.catch(err=>{$('#status').textContent=err.message;});
// Keys live only in this tab and the service worker, never in persistent storage.
window.addEventListener('pagehide',()=>{sessionKey=null;manifest=null;navigator.serviceWorker.controller?.postMessage({type:'LOCK'});});
