'use strict';
const CACHE='nmp-encrypted-v2',BASE=new URL('./',self.location.href),enc=new TextEncoder(),b64=b=>Uint8Array.from(atob(b),c=>c.charCodeAt(0));
let key=null,manifest=null,sessionPromise=null,epoch=0;
self.addEventListener('install',e=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil((async()=>{let legacy=false;for(const n of await caches.keys())if(n==='nmp-companion-v1'){legacy=true;await caches.delete(n);}await self.clients.claim();if(legacy)for(const c of await self.clients.matchAll({type:'window'}))if(c.url.startsWith(BASE.href))await c.navigate(BASE.href);})()));
self.addEventListener('message',e=>{if(e.data?.type==='UNLOCK'){key=e.data.key;manifest=e.data.manifest;epoch++;e.ports[0]?.postMessage({ok:true});}else if(e.data?.type==='LOCK'){key=null;manifest=null;epoch++;e.ports[0]?.postMessage({ok:true});}});
async function getSession(){if(key&&manifest)return true;if(sessionPromise)return sessionPromise;sessionPromise=(async()=>{for(const c of await self.clients.matchAll({type:'window',includeUncontrolled:false})){if(!c.url.startsWith(BASE.href))continue;const result=await new Promise(resolve=>{const ch=new MessageChannel(),t=setTimeout(()=>resolve({}),1500);ch.port1.onmessage=e=>{clearTimeout(t);resolve(e.data||{});};c.postMessage({type:'NEED_SESSION'},[ch.port2]);});if(result.key&&result.manifest){key=result.key;manifest=result.manifest;return true;}}return false;})();try{return await sessionPromise;}finally{sessionPromise=null;}}
async function encryptedFetch(path){const u=new URL(path,BASE),cache=await caches.open(CACHE);return await cache.match(u)||fetch(u);}
async function protectedResponse(request,rel){if(!await getSession())return new Response('Locked. Open the presentation and enter the password.',{status:401,headers:{'Cache-Control':'no-store','Content-Type':'text/plain'}});const file=manifest.files[rel];if(!file)return new Response('Not found',{status:404});const requestKey=key,requestEpoch=epoch;let start=0,end=file.size-1,status=200;const range=request.headers.get('range');if(range){const m=/^bytes=(\d*)-(\d*)$/.exec(range);if(!m||(!m[1]&&!m[2]))return invalidRange(file.size);start=m[1]?Number(m[1]):Math.max(0,file.size-Number(m[2]));end=m[1]?(m[2]?Math.min(Number(m[2]),file.size-1):file.size-1):file.size-1;if(start>end||start>=file.size)return invalidRange(file.size);status=206;}const headers={'Content-Type':file.mime,'Content-Length':String(Math.max(0,end-start+1)),'Accept-Ranges':'bytes','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Robots-Tag':'noindex, nofollow, noarchive'};if(status===206)headers['Content-Range']=`bytes ${start}-${end}/${file.size}`;if(request.method==='HEAD')return new Response(null,{status,headers});const chunkSize=manifest.chunkBytes;let i=Math.floor(start/chunkSize);const last=Math.floor(end/chunkSize);const stream=new ReadableStream({async pull(controller){try{if(requestEpoch!==epoch)throw Error('Session closed');if(i>last){controller.close();return;}const c=file.chunks[i],res=await encryptedFetch(c.url);if(!res.ok)throw Error('Asset unavailable');const data=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(c.iv),additionalData:enc.encode(rel+':'+i)},requestKey,await res.arrayBuffer()));if(requestEpoch!==epoch)throw Error('Session closed');const lo=Math.max(0,start-i*chunkSize),hi=Math.min(data.length,end-i*chunkSize+1);controller.enqueue(data.subarray(lo,hi));i++;}catch(err){controller.error(err);}}});return new Response(stream,{status,headers});}
function invalidRange(size){return new Response(null,{status:416,headers:{'Content-Range':`bytes */${size}`}});}
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(u.origin!==BASE.origin||!u.pathname.startsWith(BASE.pathname)||!['GET','HEAD'].includes(e.request.method))return;const relative=decodeURIComponent(u.pathname.slice(BASE.pathname.length));if(relative.startsWith('content/')){e.respondWith(protectedResponse(e.request,relative.slice(8)).catch(()=>new Response('Unable to decrypt asset',{status:503,headers:{'Cache-Control':'no-store'}})));return;}e.respondWith((async()=>{try{const response=await fetch(e.request);if(response.ok)return response;}catch{}const cache=await caches.open(CACHE),hit=await cache.match(e.request.url);if(hit)return hit;if(e.request.mode==='navigate')return await cache.match(BASE.href)||await cache.match(new URL('index.html',BASE))||new Response('Connect once to prepare offline access.',{status:503});return new Response('Unavailable offline',{status:503});})());});
